### ISSUE TITLE
Investigate Overlay

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/mobalytics-repackager#8]
See what other features e.g. the overlay and how they work.

May not be able to get it working though may be able to add info on how to get it working directly in wine?

**Comment by sekwah41** [comment]
Even if its just to learn something from the both of them, compare how the mac one works vs windows

**Comment by sekwah41** [comment]
Could possibly look into running command line and run the overlay exe within the wine prefix.

**Comment by sekwah41** [comment]
May be able to use /proc/%processid%/environ to find what to run the process with to get it running in the same environment

**Comment by sekwah41** [comment]
px aux | grep "C:/Riot Games/League of Legends//LeagueClient.exe"

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/140650020-cf9ed5e7-8da4-45d8-a5fe-92740423f4bd.png)
Managed to spawn task manager from within the same instance remotely, need to try to find why the overlay exe is crashing

**Comment by sekwah41** [comment]
The overlay injector process seems to be able to spawn in wine just fine using the below code

```javascript
const child_process = require('child_process');

const test = child_process.spawn('mobalytics_overlay.exe');

const {stdout, stderr} = test;
            if (stdout) {
                stdout.on('data', (data) => {
                    console.log(`stout data, data: ${data}`);
                });
                stdout.on('close', (code, signal) => {
                    console.log(`stout was closed, code: ${code}, signal: ${signal}`);
                });
                stdout.on('error', (err) => {
                    console.log(`stout error: ${err}`);
                });
                stdout.on('exit', (code, signal) => {
                    console.log(`stout exit, code: ${code}, signal: ${signal}`);
                });
                stdout.on('message', (message) => {
                    console.log(`stout, message: ${message}`);
                });
            }
            if (stderr) {
                stderr.on('data', (data) => {
                    console.log(`stderr, data: ${data}`);
                });
                stderr.on('close', (code, signal) => {
                    console.log(`stderr was closed, code: ${code}, signal: ${signal}`);
                });
                stderr.on('error', (err) => {
                    console.log(`stderr error: ${err}`);
                });
                stderr.on('exit', (code, signal) => {
                    console.log(`stderr exit, code: ${code}, signal: ${signal}`);
                });
                stderr.on('message', (message) => {
                    console.log(`stderr, message: ${message}`);
                });
            }
            test.on('close', (code, signal) => {
                console.log(`was closed, code: ${code}, signal: ${signal}`);
            });
            test.on('error', (err) => {
                console.log(`error: ${err}`);
            });
            test.on('exit', (code, signal) => {
                console.log(`exit, code: ${code}, signal: ${signal}`);
            });
            test.on('message', (message) => {
                console.log(`exit, message: ${message}`);
            });
            test.on('spawn', (message) => {
                console.log(`overlay injector spawned`, {message});
            });
            
```

**Comment by sekwah41** [comment]
At least the spawn events are triggered, need to look to create a connection layer and possibly create a new process spawner exe file using https://www.npmjs.com/package/pkg with `NODE_SKIP_PLATFORM_CHECK=1` to skip the main checks

**Comment by sekwah41** [comment]
Look for the best way to spawn and pipe the data back into the other side.

**Comment by sekwah41** [comment]
To test it you must use `export NODE_SKIP_PLATFORM_CHECK=1` and set NODE_SKIP_PLATFORM_CHECK=1 to make sure pkg will run in wine

**Comment by sekwah41** [comment]
Easiest way to test rapidly. Create a node script which you run directly trying to test the exe. Just raw everything.

**Comment by sekwah41** [comment]
```
const info = child_process_1.spawn(command, {
        shell: true,
        stdio: ['pipe', 'inherit', 'inherit'],
        env: {
            ...leagueVariables,
            NODE_SKIP_PLATFORM_CHECK: "1"
        }
    });
   ```
You can spawn processes fine inside if you have console.log outputs. However you lose access to stdout and stderr, you didn't have access anyway because of wine.

Look to make a socket pipe for any that are needed and just look for the spawn other events.

**Comment by sekwah41** [comment]
More of it is now running, possibly try moving the files within the file system first and see if it fixes wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available

**Comment by sekwah41** [comment]
https://forum.winehq.org/viewtopic.php?f=8&t=33574 may be similar error

**Comment by sekwah41** [comment]
In the most recent edits league stutters (I assume its while its injecting) just need to connect the sdout and other parts now hopefully :D

**Comment by sekwah41** [comment]
The next part is trying to figure out what electron_overlay provides

**Comment by sekwah41** [comment]
Look into https://nodejs.org/api/net.html#netcreateconnectionpath-connectlistener and using it to connect info back to the other side. Possibly try to create an IPC module restructurer.

**Comment by sekwah41** [comment]
The module is createable when the module is enabled in windows.

The main reason the overlay app can't just be run in windows is the fact that the visuals are entirely fucked for electron.

Take a look to see if it may be easier to wrap a larger part of the program in this rather than small parts. Though from now on it doesnt seem like processes but ipc messages and function calls.

**Comment by sekwah41** [comment]
https://nodejs.org/api/net.html#identifying-paths-for-ipc-connections

**Comment by sekwah41** [comment]
For now instead of IPC use sockets on specific ports then try to connect in and out of wine

**Comment by sekwah41** [comment]
possibly try connecting everything through one socket for now and add an identifier at the start. Or use env args to state the ports to connect through.

**Comment by sekwah41** [comment]
Seems `nexe` has some of its own problems but it fixes the problem of the sdout

**Comment by sekwah41** [comment]
Error with nexe instead is `Processes utils | stderr, data: node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/sekwah/.config/mobalytics-desktop/moba-extra-resources/overlay-module/1.0.0/win/electron_overlay.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sekwah/.config/mobalytics-desktop/moba-extra-resources/overlay-module/1.0.0/win/src/overlay-provider/provider-connector.js:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
`
Need to figure out why opening this file causes this error and how to properly handle process.cwd() (as its not the terminal working directory its the main parent process one?)

**Comment by sekwah41** [comment]
When switching to node windows x64-14 it seems to get Error: EINVAL: invalid argument, lstat 'Z:\'

**Comment by sekwah41** [comment]
Using a lower version of  node with pkg seems to remove the issues of pkg (though havent checked importing yet)

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/141602368-fd9fd546-4d17-4a2b-9e30-291cb6f12442.png)
now thats actually useful feedback, 100% recommend pkg over nexe

**Comment by sekwah41** [comment]
Seems the issue may be because its on the wrong drive C:\ -> Z:\ in wine

**Comment by sekwah41** [comment]
Copying files to a temp folder seems to do the trick

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/141602916-fe426f34-57db-4aad-a22a-995e213ae854.png)

**Comment by sekwah41** [comment]
Problem is uv_pipe_open issue is back, using pkg helped and seems to be better when not using wine and this specific use case

**Comment by sekwah41** [comment]
the problem is with nexe that it seems to detect that its linux and fuck everything up

**Comment by sekwah41** [comment]
Seeing as this is taking a while come back to it, try implementing a rest service or some sort of local communication (refferably without sockets) look at the/tmp/MOBA-OVERLAY-CLIENT- /tmp/MOBA-OVERLAY-SERVER and see if that works across clients

**Comment by sekwah41** [comment]
Rather than trying to do it the "right" way just get it bloody working first.

Try to use net or whatever to just enable all calls

**Comment by sekwah41** [comment]
Major fps issues found though this may be because initMemoryScannerForLoL is called every time. Check that out.

**Comment by sekwah41** [comment]
Need to look to pass the data through properly now and await the proper functions so that the data gets set. Look at `lol-internal-data/lol-memory-scanner.js`

**Comment by sekwah41** [comment]
It was an issue of the new code not accepting the async functions, needed to fix that then the init memory scanner stopped lagging

**Comment by sekwah41** [comment]
Just need to fix the window as the messages don't go through and then see whats wrong next

**Comment by sekwah41** [comment]
Looking at all the events being send its getting ALL of the data. I just need to force spawn the overlay and recode any parts which are being dodgy.

**Comment by sekwah41** [comment]
![image](https://user-images.githubusercontent.com/3209834/141665506-2650eb8c-93bc-470a-90f4-af969c8d725e.png)
Heck yea :D

**Comment by sekwah41** [comment]
Seems to be something in lol-overlay-window or base-overlay-window.

**Comment by sekwah41** [comment]
game-overlay-manager createOverlayWindow isnt even called

**Comment by sekwah41** [comment]
ensureOverlayWindow in game-overlay-manager does get called

**Comment by sekwah41** [comment]
so does createOverlayWindow making a lol overlay window

**Comment by sekwah41** [comment]
The overlay window is deffo made, so find whats not communicating now.

**Comment by sekwah41** [comment]
The overlay window controller is being made but not the this.window :thinking:

**Comment by sekwah41** [comment]
Need to find why the overlay window objects exist but not the window variable inside

**Comment by sekwah41** [comment]
If its found that the windows one wont work try looking at the mac overlay as it may not need the injection

**Comment by sekwah41** [comment]
The problems may not lie in the lol overlay as the .create function is not called. It may be to do with the base overlay or something else not being able to get size data or process id's.

**Comment by sekwah41** [comment]
There seems to be an error with the overlay server path. Going to try sockets too.

**Comment by sekwah41** [comment]
May need to convert the overlay-server to connect to a port and then pipe the data from 
```
//const CLIENT_PATH = '\\\\.\\pipe\\MOBA-OVERLAY-CLIENT-';
//const SERVER_PATH = '\\\\.\\pipe\\MOBA-OVERLAY-SERVER';
``` to the ports

**Comment by sekwah41** [comment]
Look to make a proxy on two unused ports for each of these files then rewrite how the base-overlay-server connects so that the injector written by mobalytics properly is connected.

**Comment by sekwah41** [comment]
Probably best to not rewrite the logic but to connect our own logic to where it is expecting the data. That way it can be handled solely in our connector classes.

**Comment by sekwah41** [comment]
Finally found why all the logs were not going to console, now can debug a lot more :D

**Comment by sekwah41** [comment]
Proxy is now working one way. Need to now pipe the data and dynamically create the connections going the other way.

**Comment by sekwah41** [comment]
May need to seperate the process injector to another process. Or you may be able to just keep the process around and running.

**Comment by sekwah41** [comment]
now the errors are trying to get the tmp files for specific processes.


2021-11-15T03:26:52.880Z error: Overlay server | connection to injector error, app name: league of legends.exe pid: 1604 {"error":{"errno":-2,"code":"ENOENT","syscall":"connect","address":"/tmp/MOBA-OVERLAY-CLIENT-1604"}}

**Comment by sekwah41** [comment]
An econnreset is happening likely due to this

**Comment by sekwah41** [comment]
Need to look into why translateInputEvent is returning empty data, though for now no input is better so fixed the crash error. Looking into making it interact after rendering is working.

**Comment by sekwah41** [comment]
The client constatly keeps trying to recreate the connections, so making it lazily is no issue, just need to use the connector to set it up on a free port and presto we should be good :D

**Comment by sekwah41** [comment]
For some reason, 'get-port' is suddenly messing up.

```
2021-11-21T23:52:34.639Z error: Uncaught promise exception error:  Cannot find package 'get-port' imported from /home/sekwah/.projects/mobalinux/dist/linux-unpacked/resources/app.asar/electron-src/moba-desktop/src/game-overlay/league-helper.js
Did you mean to import get-port/index.js? {"code":"ERR_MODULE_NOT_FOUND","stack":"Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'get-port' imported from /home/sekwah/.projects/mobalinux/dist/linux-unpacked/resources/app.asar/electron-src/moba-desktop/src/game-overlay/league-helper.js\nDid you mean to import get-port/index.js?\n    at packageResolve (internal/modules/esm/resolve.js:655:9)\n    at moduleResolve (internal/modules/esm/resolve.js:696:18)\n    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)\n    at Loader.resolve (internal/modules/esm/loader.js:88:40)\n    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)\n    at Loader.import (internal/modules/esm/loader.js:176:28)\n    at importModuleDynamically (internal/modules/cjs/loader.js:1018:27)\n    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)\n    at Object.<anonymous> (/home/sekwah/.projects/mobalinux/dist/linux-unpacked/resources/app.asar/electron-src/moba-desktop/src/game-overlay/league-helper.js:4:23)\n    at Module._compile (internal/modules/cjs/loader.js:1083:30)"}
error Command failed with exit code 1.

```

**Comment by sekwah41** [comment]
Need to look into whats causing the new promise issues.

**Comment by sekwah41** [comment]
Looks like most things are now connected, however there is a problem with the frame buffers being serialised. Data exists however the logic in sendFrameBuffer in base-overlay-provider errors on the OverlayIPC.Event.createEvent line.

Need to check the data being passed in and possibly try to preview one of the bitmap buffers.

**Comment by sekwah41** [comment]
For now it is not a priority though it seems pretty close to possibly working. I will have to focus on my other projects for now but ill still try to tinker with this :D

**Comment by fabifont** [comment]
Hi @sekwah41 , are you still working on this issue? It would be a great thing if you manage to have the in-game overlay working as it would be the first overlay for LoL working in Linux.

**Comment by sekwah41** [comment]
I can re-try the steps I made to see if I can get further. Last time I got pretty and managed to inject processes within the wine process to get data back, though I would need to still push the overlay data back or find another way of rendering it on top hopefully not going back within wine to avoid as much fps loss.

**Comment by fabifont** [comment]
> I can re-try the steps I made to see if I can get further. Last time I got pretty and managed to inject processes within the wine process to get data back, though I would need to still push the overlay data back or find another way of rendering it on top hopefully not going back within wine to avoid as much fps loss.
> 
> Ill add some tasks onto my organiser and see when i get around to it or have a weekend to experiment :)

Amazing. I think that also a wine version could be fine because at least we would have a working overlay even there will be less FPS (I think this is also negligible, I hope in 2023 almost everyone should be capable to run League of Legends without FPS problems)

**Comment by sekwah41** [comment]
Not sure how dodgy the stuff I was doing was so thats why I was trying to figure out.
